#!/usr/bin/env bash
set -e
snapctl set server.basepath.dir=""
snapctl set server.basepath.enforce=False
snapctl get server | $SNAP/bin/update-settings "${SNAP_DATA}/settings.conf" update
snapctl restart "${SNAP_NAME}.server"
